# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

variables: 
- group: AzureResourcesVariableGroup

trigger: none

stages:
- stage: DeployAzureResources
  jobs: 
  - job: DeployAzureResources
    pool: 
      vmImage: 'windows-latest'
    steps:

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'labAzureSubscription'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # create a resource group
          az group create -l $LOCATION -n $RESOURCEGROUPNAME

          # create and configure Azure SQL logical server and Azure SQL database
          az sql server create -l $LOCATION -g $RESOURCEGROUPNAME -n $SQLSRVNAME -u $(USERNAME) -p $(PASSWORD)
          az sql db create -g $RESOURCEGROUPNAME -s $SQLSRVNAME -n $DBNAME --service-objective Basic
          az sql server firewall-rule create -g $RESOURCEGROUPNAME -s $SQLSRVNAME -n allowazure --start-ip-address 0.0.0.0 --end-ip-address 0.0.0.0

          # create and configure an Azure App Service plan and an Azure web app
          az appservice plan create -g $RESOURCEGROUPNAME -n $SVCPLANNAME --sku FREE
          az webapp create -g $RESOURCEGROUPNAME -p $SVCPLANNAME -n $WEBAPPNAME

    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'labAzureSubscription'
        appType: 'webApp'
        WebAppName: 'mywebappgc0012'
        deployToSlotOrASE: true
        ResourceGroupName: 'aspdevops-rg'
        SlotName: 'Green'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'